seed: 42

data_dir: '../Deep-Learning-Study/MIMII/v3/data'
snr: '0_dB'

model_root: './model'

machine_types:
  - 'fan'
  - 'pump'
  - 'slider'
  - 'valve'

sr: 16000

sample_size: 4096
overlap: 2048

batch_size: 128
learning_rate: 1e-3

epoch: 1